### ISSUE TITLE
Column for address number 

### ISSUE THREAD

**Issue by luigirinaldi** [omalley242/EIE-Sandbox#10]
Add a column on the left of the input text box to quickly keep track of which address the instructions corresponds to

**Comment by luigirinaldi** [comment]
Working for EEP1, now needs to be ported to EEP0

**Comment by Diegovano** [comment]
Implemented for EEP1 in f2eb5c

Remains to port to EEP0

**Comment by luigirinaldi** [comment]
ported in EEP0
