### ISSUE TITLE
Comments in the code

### ISSUE THREAD

**Issue by luigirinaldi** [omalley242/EIE-Sandbox#11]
Implement a way to comment, probably with "//" but other ways could be interesting

**Comment by luigirinaldi** [comment]
closed by accident

**Comment by tomcl** [comment]
For EEP1  comments only partially work
// comment works for jumps

JMP #3 // comment is ok

But not for ALU operations:
MOV R0, R1 // comment does not work
MOV R0, R1, #1 // comment does not work
MOV R0, #100 // comment does not work

Nor for comments on empty lines
// comment does not work

In all error cases there is a line syntax error when I expect no error.
Comments could be implemented by pre-processing lines, splitting at "//" and discarding all after first element of split list.
If that works in JS

**Comment by Diegovano** [comment]
It turns out this was not _supposed_ to be a feature, at least yet.... We have reverted back to before the refactor that introduced a number of issues (1f619b0f49738465b322dbc5eb8b5883f2ec0bd3), and will be working on debugging that refactor on the develop branch.

**Comment by tomcl** [comment]
Well, just to say that the reverted code is not quite as good as before: no ability to download a .ram file, otherwise the same.
